// src/lib/apps/Contact.svelte
<script lang="ts">
	// Contact information component styled like a simple notepad
</script>

<div class="bg-gray-50 font-body text-sm p-6 leading-relaxed">
	<h2 class="font-bold text-xl mb-6 text-gray-900">Get In Touch</h2>
	
	<div class="space-y-4">
		<div>
			<strong class="text-gray-700">Name:</strong> <span class="text-gray-900">Eshan Khan</span>
		</div>
		
		<div>
			<strong class="text-gray-700">Email:</strong> 
			<a href="mailto:eakhan37@gmail.com" class="text-teal-600 hover:text-teal-500 underline transition-colors">
				eakhan37@gmail.com
			</a>
		</div>
		
		<div>
			<strong class="text-gray-700">Location:</strong> <span class="text-gray-900">Boyds, MD</span>
		</div>
		
		<div>
			<strong class="text-gray-700">University:</strong> <span class="text-gray-900">University of Maryland, College Park</span>
		</div>
		
		<div class="mt-8 pt-6 border-t border-gray-300">
			<strong class="text-gray-700 block mb-3">Connect with me:</strong>
			<div class="space-y-3">
				<div>
					<a 
						href="https://github.com/eshan327" 
						target="_blank" 
						rel="noopener noreferrer"
						class="inline-flex items-center gap-2 text-teal-600 hover:text-teal-500 transition-colors group"
					>
						<span class="text-lg">🖥️</span>
						<span class="underline">GitHub Profile</span>
						<span class="opacity-0 group-hover:opacity-100 transition-opacity">→</span>
					</a>
				</div>
				<div>
					<a 
						href="https://www.linkedin.com/in/eshankhan05" 
						target="_blank" 
						rel="noopener noreferrer"
						class="inline-flex items-center gap-2 text-teal-600 hover:text-teal-500 transition-colors group"
					>
						<span class="text-lg">🔗</span>
						<span class="underline">LinkedIn Profile</span>
						<span class="opacity-0 group-hover:opacity-100 transition-opacity">→</span>
					</a>
				</div>
				<div>
					<a 
						href="/Resume.pdf" 
						target="_blank" 
						rel="noopener noreferrer"
						class="inline-flex items-center gap-2 text-teal-600 hover:text-teal-500 transition-colors group"
					>
						<span class="text-lg">📄</span>
						<span class="underline">Download Resume</span>
						<span class="opacity-0 group-hover:opacity-100 transition-opacity">→</span>
					</a>
				</div>
			</div>
		</div>
		
		<div class="mt-8 p-4 bg-teal-50 border-l-4 border-teal-500 rounded">
			<p class="text-gray-700 text-sm">
				<strong class="text-teal-700">Open to opportunities!</strong><br/>
				I'm actively seeking internships and full-time roles in software engineering and AI/ML.
			</p>
		</div>
	</div>
</div>

// src/app/contact/page.tsx
'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { EnvelopeClosedIcon, GitHubLogoIcon, LinkedInLogoIcon } from '@radix-ui/react-icons';
import PageTransition from '../components/PageTransition';

export default function Contact() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    message: '',
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Handle form submission
    console.log(formData);
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  return (
    <PageTransition>
      <div className="max-w-4xl mx-auto px-4 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <h1 className="text-4xl font-bold mb-4 gradient-text">Get in Touch</h1>
          <p className="text-gray-600 dark:text-gray-300">
            Have a question or want to work together? Feel free to reach out!
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-12">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="space-y-8"
          >
            <div className="glass p-6 rounded-xl">
              <h2 className="text-2xl font-semibold mb-4">Contact Information</h2>
              <div className="space-y-4">
                <a
                  href="mailto:eshan327@gmail.com"
                  className="flex items-center gap-3 text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
                >
                  <EnvelopeClosedIcon className="w-5 h-5" />
                  <span>eshan327@gmail.com</span>
                </a>
                <a
                  href="https://github.com/eshan327"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-3 text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
                >
                  <GitHubLogoIcon className="w-5 h-5" />
                  <span>github.com/eshan327</span>
                </a>
                <a
                  href="https://linkedin.com/in/eshan327"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-3 text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
                >
                  <LinkedInLogoIcon className="w-5 h-5" />
                  <span>linkedin.com/in/eshan327</span>
                </a>
              </div>
            </div>

            <div className="glass p-6 rounded-xl">
              <h2 className="text-2xl font-semibold mb-4">Location</h2>
              <div className="relative">
                <div className="absolute inset-0 bg-gradient-to-br from-blue-500/20 to-purple-500/20 rounded-lg blur-xl" />
                <div className="relative p-4 rounded-lg border border-white/10">
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
                    <span className="text-lg font-medium">University of Maryland</span>
                  </div>
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-2 h-2 rounded-full bg-purple-500 animate-pulse" style={{ animationDelay: '0.5s' }} />
                    <span className="text-lg">College Park, MD</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" style={{ animationDelay: '1s' }} />
                    <span className="text-lg">United States</span>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>

          <motion.form
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4 }}
            onSubmit={handleSubmit}
            className="glass p-6 rounded-xl space-y-6"
          >
            <div>
              <label htmlFor="name" className="block text-sm font-medium mb-2">
                Name
              </label>
              <input
                type="text"
                id="name"
                name="name"
                value={formData.name}
                onChange={handleChange}
                className="w-full px-4 py-2 rounded-lg bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                required
              />
            </div>

            <div>
              <label htmlFor="email" className="block text-sm font-medium mb-2">
                Email
              </label>
              <input
                type="email"
                id="email"
                name="email"
                value={formData.email}
                onChange={handleChange}
                className="w-full px-4 py-2 rounded-lg bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                required
              />
            </div>

            <div>
              <label htmlFor="message" className="block text-sm font-medium mb-2">
                Message
              </label>
              <textarea
                id="message"
                name="message"
                value={formData.message}
                onChange={handleChange}
                rows={6}
                className="w-full px-4 py-2 rounded-lg bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                required
              />
            </div>

            <motion.button
              type="submit"
              className="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 rounded-lg hover:shadow-lg transition-all hover-lift"
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              Send Message
            </motion.button>
          </motion.form>
        </div>
      </div>
    </PageTransition>
  );
}
